name: gpu-test-base.yml
on:
  push:
    branches:
      - 'eagle1'
  pull_request:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [electron, chrome, chromium, edge, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}

  debug:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [electron, chrome, chromium, edge, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run debug
        uses: cypress-io/github-action@v5
        env:
          DEBUG: '@cypress/github-action, cypress:*'
        with:
          browser: ${{ matrix.browser }}
